apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: backend-inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://postgres-inventory:5432/inventory_db

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: password

            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"

            - name: KAFKA_SERVERS
              value: kafka:29092