spring.application.name=gateway-service

server.port=8080

# Order Service
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://order-service:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/orders(?<segment>/?.*), /orders${segment}

# Inventory Service
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=http://inventory-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/inventory(?<segment>/?.*), /inventory${segment}

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173,http://ecommerce.local:8088
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials