apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: backend-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_MONGODB_URI
              value: mongodb://mongodb:27017/ecommerce

            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"

            - name: KAFKA_SERVERS
              value: kafka:29092

            - name: INVENTORY_SERVICE_URL
              value: http://inventory-service:8081/inventory